### PR TITLE
Update Rust side dependencies

### PR DESCRIPTION
**Pull request by liushuyu**
In this PR, the following changes were made:

- The dependencies are updated to their latest versions except for `hyper` `futures` and `reqwest` which may require a code refactor
   - The `web-view` crate is replaced with the one on `crate.io` now, and the fixes are included. Also, the crate now gained the ability to use Microsoft Edge as the renderer instead of IE 11.
- The code standard has been updated to Rust 2018. The corresponding flags are added to the manifest file, and the compiler will enforce the new standard from now on.
- Added Windows support-level flags to the `build.rs` to fix the build on Windows.

---
This change is [Reviewable](https://reviewable.io/reviews/j-selby/liftinstall/31)

### CODE REVIEW

**Comment by liushuyu** [comment]
>Super sorry for not getting around to this earlier - the updated webview does appear to have additional requirements (https://github.com/j-selby/liftinstall/pull/31/files#diff-553060167c186166f7e00d2f6fea45caL41) - is this something you can address in this?

It currently still functions fine without additional crates. This one indicates you need to use a separate crate to implement file dialog function (because in the future they will remove the API)

>Further, were you able to get the Edge frontend working? From what I understand, it wasn't able to connect to the local server last I checked.

From what I know, this requires to [bypass UWP application's local loopback isolation](https://docs.microsoft.com/en-us/previous-versions/windows/apps/dn640582(v=win.10)). Microsoft explained that this is a security feature.

**Comment by j-selby** [comment]
`It currently still functions fine without additional crates. This one indicates you need to use a separate crate to implement file dialog function (because in the future they will remove the API)`

Ok, fair enough.

`From what I know, this requires to bypass UWP application's local loopback isolation. Microsoft explained that this is a security feature.`

Yeah - saw that, though I was never able to toggle this (it seems that the Win32 APIs don't allow for this?).

**Comment by liushuyu** [comment]
>Yeah - saw that, though I was never able to toggle this (it seems that the Win32 APIs don't allow for this?).

AFAIK, you can only toggle this behaviour on each app basis. And the permission settings seem to be stored in the registry (I could be wrong though).

**Comment by j-selby** [comment]
Na, all good - something to investigate down the line (as long as they don't remove the IE frontend in the meantime).

**Pull request merged**
